---
# Arch Linux packages installable via pacman
arch_pacman_packages:
  # Base system packages
  - base-devel
  - curl
  - jq
  - openssh
  - unzip
  - xclip
  - polkit
  - iwd
  - brightnessctl
  - power-profiles-daemon
  - fastfetch
  - docker
  - docker-compose
  - bluetui

  # CLI tools
  - bat
  - btop
  - git-delta
  - dust
  - fd
  - fzf
  - just
  - less
  - ripgrep
  - sheldon
  - zellij
  - zoxide
  - zsh

  # Development tools
  - neovim
  - imagemagick
  - luarocks
  - python
  - nvm

  # GUI applications
  - ghostty
  - i3-wm
  - i3status
  - rofi
  - nautilus

  # Hyprland and related tools
  - hyprland
  - dunst
  - hyprpaper
  - grim
  - wl-clipboard
  - hyprpicker
  - hyprpolkitagent
  - hyprlock
  - hypridle
  - waybar

  # Audio
  - pipewire
  - pipewire-pulse
  - wireplumber
  - pamixer
  - playerctl
