---
# Arch Linux packages installable via pacman
arch_pacman_packages:
  # Base system packages
  - base-devel
  - curl
  - jq
  - openssh
  - unzip
  - xclip
  - polkit
  - iwd
  - brightnessctl
  - power-profiles-daemon
  - fastfetch
  - docker
  - docker-compose
  - bluetui

  # Fonts
  - noto-fonts-emoji 
  - noto-fonts-cjk 
  - ttf-nerd-fonts-symbols-mono
  - otf-font-awesome

  # CLI tools
  - bat
  - btop
  - git-delta
  - dust
  - fd
  - fzf
  - just
  - less
  - ripgrep
  - sheldon
  - zellij
  - zoxide
  - zsh

  # Development tools
  - neovim
  - imagemagick
  - luarocks
  - python
  - github-cli
  - tree-sitter-cli
  - bash-language-server
  - ansible-language-server
  - lua-language-server
  - yaml-language-server
  - harper
  - tinymist

  # GUI applications
  - ghostty
  - i3-wm
  - i3status
  - rofi
  - nautilus
  - obsidian

  # Hyprland and related tools
  - hyprland
  - dunst
  - hyprpaper
  - wl-clipboard
  - hyprpicker
  - hyprpolkitagent
  - hyprlock
  - hypridle
  - waybar
  - qt5-wayland
  - qt6-wayland
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-gtk

  # Audio
  - pipewire
  - pipewire-pulse
  - wireplumber
  - pamixer
  - playerctl

  # Typesettings
  - ghostscript
  - tectonic
  - mermaid-cli
  - python-pylatexenc
