---
# Ubuntu packages installable via apt
ubuntu_apt_packages:
  - build-essential
  - curl
  - jq
  - openssh-client
  - unzip
  - xclip
  - imagemagick
  - libmagickwand-dev
  - luarocks
  - python3-venv
  - i3
  - i3status
  - rofi
  - zsh

# Ubuntu packages to install via cargo (when apt version doesn't exist or is outdated)
ubuntu_cargo_packages:
  - ripgrep
  - fd-find
  - du-dust
  - lsd
  - zoxide
