---
- name: Install GNU Stow (Arch Linux)
  become: true
  community.general.pacman:
    name: stow
    state: present
  when: ansible_facts["distribution"] == "Archlinux"

- name: Install GNU Stow (Ubuntu)
  become: true
  ansible.builtin.apt:
    name: stow
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Build directories list
  ansible.builtin.find:
    paths: [dotfiles/]
    recurse: no
    file_type: directory
  register: files

- name: Deploy dotfiles
  become: true
  with_items: '{{ files.files }}'
  ansible.builtin.shell: |
    STOW_PATH={{ item.path | replace("dotfiles/", "") }}
    OVERRIDE_TARGET=$(cat ${STOW_PATH}/.override 2>/dev/null)
    TARGET=${OVERRIDE_TARGET:-{{ ansible_facts.env.HOME }}}
    stow -v -t ${TARGET} ${STOW_PATH}
  args:
    chdir: ./dotfiles
    executable: /bin/bash
  loop_control:
    label: |-
      {% if output.stderr|length > 1 %}
      {{ item.path }}
      {{ output.stderr }}
      {%- else %}
      {{ item.path }}
      {%- endif %}
  register: output
  changed_when: '"LINK" in output.stderr'
