---
- name: Install uv in Ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install uv in Arch Linux
  ansible.builtin.import_tasks: arch.yml
  when: ansible_distribution == "Archlinux"
