---
- name: Check if uv is installed
  ansible.builtin.shell: command -v uv
  register: uv_exists
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Install uv
  ansible.builtin.shell: curl -LsSf https://astral.sh/uv/install.sh | sh
  when: uv_exists.rc != 0
