---
- name: Install Ghostty in Ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install Ghostty in Arch Linux
  ansible.builtin.import_tasks: arch.yml
  when: ansible_facts["distribution"] == "Archlinux"
