---
- name: Install X11 utilities in Ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install X11 utilities in Arch Linux
  ansible.builtin.import_tasks: arch.yml
  when: ansible_facts["distribution"] == "Archlinux"
