# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.supercharge]
github = "zap-zsh/supercharge"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.aliases]
local = "~/.config/zsh/"
use = ["aliases.zsh"]

[plugins.exports]
local = "~/.config/zsh/"
use = ["exports.zsh"]

[plugins.functions]
local = "~/.config/zsh/"
use = ["functions.zsh"]

# Do not store important secrets, as this method is not secure! This is intended for
# things like unimportant API keys and the like. secrets.zsh is not tracked by git.
[plugins.secrets]
inline = '''
if [ -f "$HOME/.config/zsh/secrets.zsh" ]; then
  source "$HOME/.config/zsh/secrets.zsh"
fi
'''
