---
- name: Restart greetd
  become: true
  ansible.builtin.systemd:
    name: greetd.service
    state: restarted
  failed_when: false

- name: systemd daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  failed_when: false
  when: ansible_facts["service_mgr"] == "systemd"
