---
- name: Install dust in Ubuntu
  community.general.cargo:
    name: du-dust
    executable: "{{ cargo_path }}"
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install dust in Arch Linux
  become: true
  community.general.pacman:
    name: dust
    state: present
  when: ansible_facts["distribution"] == "Archlinux"
